import { listAgents } from "../agents";
import { listProjects, getProject } from "../projects";
import { listRoles } from "../roles";
import {
  addTaskAttachment,
  addTaskDependency,
  addTaskFileReference,
  addTaskTodo,
  approveLaneCompletion,
  approveTaskReview,
  archiveMailboxMessages,
  commentOnTask,
  completeLaneAsFailure,
  completeLaneAsSuccess,
  createContextualSession,
  createSession,
  createTask,
  createTaskSchedule,
  deleteSession,
  deleteTask,
  deleteTaskComment,
  deleteTaskSchedule,
  deleteTaskTodo,
  dispatchTaskLane,
  getAppInfo,
  getSessionModelState,
  getSessionRecord,
  getSessionRuntimeDetails,
  getSessionStats,
  getTask,
  getTaskFileContent,
  getTaskSchedule,
  getWorkflow,
  listInboxMessages,
  listSessions,
  listTaskComments,
  listTaskFileReferences,
  listTaskMessages,
  listTaskSchedules,
  listTaskTodos,
  listTasks,
  listUnfinishedTaskTodos,
  listWorkflows,
  manualTaskWhip,
  markMailboxMessagesRead,
  markTaskCommentsReadForUser,
  markTaskNeedsWork,
  markTaskTodoFinished,
  markTaskTodoUnfinished,
  pauseTaskLane,
  reassignTaskToLane,
  reloadSession,
  removeTaskAttachment,
  removeTaskDependency,
  removeTaskFileReference,
  reportClientError,
  requestUserIntervention,
  resetTaskRuntime,
  resumeSession,
  resumeTaskLane,
  searchTaskCommentFileMentions,
  sendMailboxMessage,
  sendSessionMessage,
  setDefaultTaskFileReference,
  setSessionModel,
  stopSessionRuntime,
  stopTaskActivity,
  subscribeSession,
  compactSession,
  unsubscribeSession,
  updateTask,
  updateTaskComment,
  updateTaskSchedule,
} from "../tauri";
import type {
  OrchestraTaskCompletionOutcome,
} from "./client";
import type { OrchestraClientServiceBindings } from "./serviceBindings";

async function completeTask(
  taskId: string,
  outcome: OrchestraTaskCompletionOutcome,
  notes?: string,
) {
  switch (outcome) {
    case "success":
      return completeLaneAsSuccess(taskId, notes);
    case "failure":
      return completeLaneAsFailure(taskId, notes);
    case "needs_user":
      return requestUserIntervention(taskId, notes);
    default:
      return requestUserIntervention(taskId, notes);
  }
}

export const mockOrchestraClientServiceBindings: OrchestraClientServiceBindings = {
  app: {
    getInfo: getAppInfo,
    reportError: reportClientError,
  },
  catalog: {
    listProjects,
    getProject,
    listAgents,
    listRoles,
    listWorkflows,
    getWorkflow,
  },
  tasks: {
    list: listTasks,
    get: getTask,
    create: createTask,
    update: updateTask,
    remove: deleteTask,
    listTodos: listTaskTodos,
    listUnfinishedTodos: listUnfinishedTaskTodos,
    addTodo: addTaskTodo,
    markTodoFinished: markTaskTodoFinished,
    markTodoUnfinished: markTaskTodoUnfinished,
    deleteTodo: deleteTaskTodo,
    listComments: listTaskComments,
    comment: commentOnTask,
    updateComment: updateTaskComment,
    deleteComment: deleteTaskComment,
    markCommentsRead: markTaskCommentsReadForUser,
    searchCommentFileMentions: searchTaskCommentFileMentions,
    listMessages: listTaskMessages,
    addDependency: addTaskDependency,
    removeDependency: removeTaskDependency,
    listFileReferences: listTaskFileReferences,
    addFileReference: addTaskFileReference,
    setDefaultFileReference: setDefaultTaskFileReference,
    removeFileReference: removeTaskFileReference,
    getFileContent: getTaskFileContent,
    addAttachment: addTaskAttachment,
    removeAttachment: removeTaskAttachment,
    listSchedules: listTaskSchedules,
    getSchedule: getTaskSchedule,
    createSchedule: createTaskSchedule,
    updateSchedule: updateTaskSchedule,
    deleteSchedule: deleteTaskSchedule,
    dispatch: dispatchTaskLane,
    complete: completeTask,
    approveReview: approveTaskReview,
    approveCompletion: approveLaneCompletion,
    markNeedsWork: markTaskNeedsWork,
    resume: resumeTaskLane,
    pause: pauseTaskLane,
    stopActivity: stopTaskActivity,
    reassign: reassignTaskToLane,
    manualWhip: manualTaskWhip,
    resetRuntime: resetTaskRuntime,
  },
  inbox: {
    list: listInboxMessages,
    send: sendMailboxMessage,
    markRead: markMailboxMessagesRead,
    archive: archiveMailboxMessages,
  },
  sessions: {
    list: listSessions,
    get: getSessionRecord,
    getRuntimeDetails: getSessionRuntimeDetails,
    getStats: getSessionStats,
    create: createSession,
    createContextual: createContextualSession,
    remove: deleteSession,
    resume: resumeSession,
    subscribe: subscribeSession,
    unsubscribe: unsubscribeSession,
    stopRuntime: stopSessionRuntime,
    getModelState: getSessionModelState,
    setModel: setSessionModel,
    compact: compactSession,
    reload: reloadSession,
    sendMessage: sendSessionMessage,
  },
};
