import {
  archiveAgent,
  createAgent,
  deleteAgentQueueEntry,
  enqueueAgentWork,
  ensureAgentSession,
  getAgent,
  getAgentMemoryInfo,
  getAgentOperations,
  listAgentOperations,
  listAgents,
  updateAgent,
  updateAgentMainSession,
  validateAgent,
} from "../agents";
import {
  createChannel,
  deleteChannel,
  getChannel,
  listChannelActivity,
  listChannels,
  listTelegramChatCandidates,
  updateChannel,
  validateTelegramBot,
} from "../channels";
import {
  getAgentPermissions,
  getPolicy,
  getRolePermissions,
  listPolicies,
} from "../policies";
import {
  createProjectSecret,
  deleteProjectSecret,
  getProjectSecrets,
  getSessionPromptSettings,
  getTaskAutomationSettings,
  getWorkerOverlay,
  updateProjectSecret,
  updateSessionPromptSettings,
  updateTaskAutomationSettings,
  updateWorkerOverlay,
} from "../projectSettings";
import {
  attachRepositoryRemote,
  createProject,
  createRepository,
  deleteProject,
  deleteRepository,
  getProject,
  getRepository,
  listProjects,
  listRepositories,
  setProjectDefaultRepository,
  updateProject,
  updateRepository,
} from "../projects";
import {
  archiveRole,
  createRole,
  getRole,
  listRoles,
  updateRole,
  validateRole,
} from "../roles";
import {
  deleteRoleQueueEntry,
  dispatchRoleQueue,
  disposeRoleInstance,
  enqueueRoleWork,
  getRoleOperations,
  listRoleOperations,
  releaseRoleInstance,
  resetRoleAssignments,
} from "../roleRuntime";
import {
  getProjectSourceControlSettings,
  getSourceControlSettings,
  updateProjectSourceControlSettings,
  updateSourceControlSettings,
} from "../sourceControlSettings";
import {
  copyProjectNote,
  copyProjectNotesDirectory,
  createProjectNotesDirectory,
  deleteProjectNote,
  deleteProjectNotesDirectory,
  getProjectNote,
  listProjectNotes,
  moveProjectNote,
  moveProjectNotesDirectory,
  updateProjectNote,
} from "../projectNotes";
import {
  addTaskAttachment,
  addTaskDependency,
  addTaskFileReference,
  addTaskTodo,
  approveLaneCompletion,
  approveTaskReview,
  archiveMailboxMessages,
  archiveWorkflow,
  commentOnTask,
  deleteWorkflow,
  completeLaneAsFailure,
  completeLaneAsSuccess,
  createContextualSession,
  createSession,
  createTask,
  createTaskSchedule,
  createWorkflow,
  deleteSession,
  deleteTask,
  deleteTaskComment,
  deleteTaskSchedule,
  getTaskCommentDeleteImpact,
  deleteTaskTodo,
  dispatchTaskLane,
  duplicateWorkflow,
  downloadTaskAttachment,
  getAppInfo,
  getPiExecutableDiagnostic,
  getSessionModelState,
  getSessionRecord,
  getSessionRuntimeDetails,
  getSessionStats,
  getTask,
  getTaskFileContent,
  getTaskPullRequest,
  getTaskSchedule,
  getWorkflow,
  getWorkflowDeleteImpact,
  listInboxMessages,
  listPiModels,
  listSessions,
  listTaskComments,
  listTaskFileReferences,
  listTaskMessages,
  listTaskSchedules,
  listTaskTodos,
  listTasks,
  listUnfinishedTaskTodos,
  listWorkflows,
  manualTaskWhip,
  markMailboxMessagesRead,
  markTaskCommentsReadForUser,
  markTaskNeedsWork,
  markTaskTodoFinished,
  markTaskTodoUnfinished,
  pauseTaskLane,
  reassignTaskToLane,
  reloadSession,
  removeTaskAttachment,
  removeTaskDependency,
  removeTaskFileReference,
  reportClientError,
  requestUserIntervention,
  resetTaskRuntime,
  resumeSession,
  resumeTaskLane,
  searchTaskCommentFileMentions,
  sendMailboxMessage,
  sendSessionMessage,
  setDefaultTaskFileReference,
  setSessionModel,
  stopSessionRuntime,
  stopTaskActivity,
  subscribeSession,
  compactSession,
  unsubscribeSession,
  updateTask,
  updateTaskComment,
  updateTaskSchedule,
  updateWorkflow,
  validateWorkflow,
} from "../tauri";
import type {
  OrchestraTaskCompletionOutcome,
} from "./client";
import type { OrchestraClientServiceBindings } from "./serviceBindings";

async function completeTask(
  taskId: string,
  outcome: OrchestraTaskCompletionOutcome,
  summary: string,
  notes?: string,
) {
  switch (outcome) {
    case "success":
      return completeLaneAsSuccess(taskId, summary, notes);
    case "failure":
      return completeLaneAsFailure(taskId, summary, notes);
    case "needs_user":
      return requestUserIntervention(taskId, summary, notes);
    default:
      return requestUserIntervention(taskId, summary, notes);
  }
}

function unsupportedManagedSkillsError() {
  return new Error("Managed skills are unavailable in the mock host.");
}

export const mockOrchestraClientServiceBindings: OrchestraClientServiceBindings = {
  app: {
    getInfo: getAppInfo,
    reportError: reportClientError,
  },
  catalog: {
    listProjects,
    getProject,
    listAgents,
    listRoles,
    listWorkflows,
    getWorkflow,
  },
  projects: {
    createProject,
    updateProject,
    deleteProject,
    listRepositories,
    getRepository,
    createRepository,
    updateRepository,
    deleteRepository,
    attachRepositoryRemote,
    setProjectDefaultRepository,
  },
  settings: {
    listPiModels,
    getPiExecutableDiagnostic,
    getSourceControlSettings,
    updateSourceControlSettings,
    getProjectSourceControlSettings,
    updateProjectSourceControlSettings,
    getSessionPromptSettings,
    updateSessionPromptSettings,
    getTaskAutomationSettings,
    updateTaskAutomationSettings,
    getWorkerOverlay,
    updateWorkerOverlay,
    getProjectSecrets,
    createProjectSecret,
    updateProjectSecret,
    deleteProjectSecret,
  },
  workers: {
    validateAgent,
    getAgent,
    createAgent,
    updateAgent,
    archiveAgent,
    getAgentMemoryInfo,
    listAgentOperations,
    getAgentOperations,
   ensureAgentSession,
    updateAgentMainSession,
    enqueueAgentWork,
    deleteAgentQueueEntry,
    getAgentPermissions,
    validateRole,
    getRole,
    createRole,
    updateRole,
    archiveRole,
    listRoleOperations,
    getRoleOperations,
    enqueueRoleWork,
    dispatchRoleQueue,
    deleteRoleQueueEntry,
    resetRoleAssignments,
    releaseRoleInstance,
    disposeRoleInstance,
    getRolePermissions,
  },
  workflows: {
    validateWorkflow,
    createWorkflow,
    updateWorkflow,
    duplicateWorkflow,
    archiveWorkflow,
    getWorkflowDeleteImpact,
    deleteWorkflow,
  },
  policies: {
    listPolicies,
    getPolicy,
  },
  channels: {
    listChannels,
    getChannel,
    listChannelActivity,
    createChannel,
    updateChannel,
    deleteChannel,
    validateTelegramBot,
    listTelegramChatCandidates,
  },
  skills: {
    listSkills: async () => { throw unsupportedManagedSkillsError(); },
    getSkill: async () => { throw unsupportedManagedSkillsError(); },
    getCatalogDiagnostics: async () => { throw unsupportedManagedSkillsError(); },
    createLocalSkill: async () => { throw unsupportedManagedSkillsError(); },
    updateLocalSkill: async () => { throw unsupportedManagedSkillsError(); },
    archiveLocalSkill: async () => { throw unsupportedManagedSkillsError(); },
    unarchiveLocalSkill: async () => { throw unsupportedManagedSkillsError(); },
    deleteLocalSkill: async () => { throw unsupportedManagedSkillsError(); },
    refreshExternalSkills: async () => { throw unsupportedManagedSkillsError(); },
    setSkillBindings: async () => { throw unsupportedManagedSkillsError(); },
    getRoleSkillLinks: async () => { throw unsupportedManagedSkillsError(); },
    getAgentSkillLinks: async () => { throw unsupportedManagedSkillsError(); },
    getWorkflowSkillLinks: async () => { throw unsupportedManagedSkillsError(); },
  },
  notes: {
    list: listProjectNotes,
    get: getProjectNote,
    update: updateProjectNote,
    delete: deleteProjectNote,
    copy: copyProjectNote,
    move: moveProjectNote,
    createDirectory: createProjectNotesDirectory,
    deleteDirectory: deleteProjectNotesDirectory,
    copyDirectory: copyProjectNotesDirectory,
    moveDirectory: moveProjectNotesDirectory,
  },
  tasks: {
    list: listTasks,
    get: getTask,
    create: createTask,
    update: updateTask,
    remove: deleteTask,
    listTodos: listTaskTodos,
    listUnfinishedTodos: listUnfinishedTaskTodos,
    addTodo: addTaskTodo,
    markTodoFinished: markTaskTodoFinished,
    markTodoUnfinished: markTaskTodoUnfinished,
    deleteTodo: deleteTaskTodo,
    listComments: listTaskComments,
    comment: commentOnTask,
    updateComment: updateTaskComment,
    deleteComment: deleteTaskComment,
    showBrowser: async () => { throw new Error("Task browser is only available in the desktop Tauri shell."); },
    getBrowserState: async () => { throw new Error("Task browser is only available in the desktop Tauri shell."); },
    navigateBrowser: async () => { throw new Error("Task browser is only available in the desktop Tauri shell."); },
    setBrowserInspectMode: async () => { throw new Error("Task browser is only available in the desktop Tauri shell."); },
    revealBrowserDomAnchor: async () => { throw new Error("Task browser is only available in the desktop Tauri shell."); },
    getCommentDeleteImpact: getTaskCommentDeleteImpact,
    markCommentsRead: markTaskCommentsReadForUser,
    searchCommentFileMentions: searchTaskCommentFileMentions,
    listMessages: listTaskMessages,
    addDependency: addTaskDependency,
    removeDependency: removeTaskDependency,
    listFileReferences: listTaskFileReferences,
    addFileReference: addTaskFileReference,
    setDefaultFileReference: setDefaultTaskFileReference,
    removeFileReference: removeTaskFileReference,
    getFileContent: getTaskFileContent,
    getPullRequest: getTaskPullRequest,
    addAttachment: addTaskAttachment,
    downloadAttachment: downloadTaskAttachment,
    removeAttachment: removeTaskAttachment,
    listSchedules: listTaskSchedules,
    getSchedule: getTaskSchedule,
    createSchedule: createTaskSchedule,
    updateSchedule: updateTaskSchedule,
    deleteSchedule: deleteTaskSchedule,
    dispatch: dispatchTaskLane,
    complete: completeTask,
    approveReview: approveTaskReview,
    approveCompletion: approveLaneCompletion,
    markNeedsWork: markTaskNeedsWork,
    resume: resumeTaskLane,
    pause: pauseTaskLane,
    stopActivity: stopTaskActivity,
    reassign: reassignTaskToLane,
    manualWhip: manualTaskWhip,
    resetRuntime: resetTaskRuntime,
  },
  inbox: {
    list: listInboxMessages,
    send: sendMailboxMessage,
    markRead: markMailboxMessagesRead,
    archive: archiveMailboxMessages,
  },
  sessions: {
    list: listSessions,
    get: getSessionRecord,
    getRuntimeDetails: getSessionRuntimeDetails,
    getStats: getSessionStats,
    create: createSession,
    createContextual: createContextualSession,
    remove: deleteSession,
    resume: resumeSession,
    subscribe: subscribeSession,
    unsubscribe: unsubscribeSession,
    stopRuntime: stopSessionRuntime,
    getModelState: getSessionModelState,
    setModel: setSessionModel,
    compact: compactSession,
    reload: reloadSession,
    sendMessage: sendSessionMessage,
  },
};
